//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbConstants
// {
//
//   uint batch_idx;                    // Offset:    0 Size:     4 [unused]
//   uint tex_diffuse;                  // Offset:    4 Size:     4
//   float alpha;                       // Offset:    8 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// sam                               sampler      NA          NA             s0      1 
// tex_map                           texture  float4          2d             t0      1 
// cbConstants                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 4
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v2.xyxx, t0.xyzw, s0
add r1.x, r0.w, l(-0.500000)
lt r1.x, r1.x, l(0.000000)
discard_nz r1.x
log r1.xyz, r0.xyzx
mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r1.xyz, r1.xyzx
mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
mul r3.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
movc r0.xyz, r2.xyzx, r3.xyzx, r1.xyzx
utof r1.x, cb0[0].y
mul r0.xyzw, r0.xyzw, r1.xxxx
iadd r1.x, -cb0[0].y, l(1)
utof r1.x, r1.x
mad r0.xyzw, v1.xyzw, r1.xxxx, r0.xyzw
mul o0.w, r0.w, cb0[0].z
mov o0.xyz, r0.xyzx
ret 
// Approximately 19 instruction slots used
